const firebaseConfig={apiKey:'AIzaSyD_Hbkc00HfJDmtw-2KSR4b9AbsThFt8vg',authDomain:'mopyonlakay.firebaseapp.com',projectId:'mopyonlakay',storageBucket:'mopyonlakay.firebasestorage.app',messagingSenderId:'307157893690',appId:'1:307157893690:web:4e5a033d13d54ce86feb03'};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),functions=firebase.app().functions('us-central1'),params=new URLSearchParams(location.search),intentId=params.get('intent')||sessionStorage.getItem('jwetpro_last_ticket_intent')||'',statusNode=document.getElementById('status'),form=document.getElementById('login-form');
const setStatus=(message,type='')=>{statusNode.textContent=message;statusNode.className=`status ${type}`.trim();};
let checks=0,timer;
async function verify(){if(!intentId){setStatus('Référence d’inscription introuvable.','error');return;}try{const result=await functions.httpsCallable('getChampionshipRegistrationStatus')({intentId}),data=result.data||{};if(data.status==='paid'){document.getElementById('return-title').textContent='Inscription confirmée';document.getElementById('return-copy').textContent='Votre ticket est validé et votre place est enregistrée.';setStatus('Paiement confirmé. Vous êtes inscrit au championnat.','success');const shareButton=document.getElementById('share-registration');shareButton.dataset.championshipId=data.championshipId||'';shareButton.hidden=!data.championshipId;return;}if(data.status==='credited'){document.getElementById('return-title').textContent='Montant transformé en crédit';document.getElementById('return-copy').textContent='La place n’était plus disponible au moment de la confirmation. Aucun argent n’est perdu.';setStatus(`Crédit JwetPro disponible : ${new Intl.NumberFormat('fr-HT').format(Number(data.creditAmount)||0)} HTG.`,'success');return;}checks+=1;setStatus(`Paiement en cours de vérification (${data.status||'en attente'}).`);if(checks<20)timer=setTimeout(verify,5000);else setStatus('La confirmation prend plus de temps que prévu. Revenez sur cette page dans quelques minutes.','error');}catch(error){setStatus(error.message||'Vérification indisponible.','error');}}
form.addEventListener('submit',async event=>{event.preventDefault();try{await auth.signInWithEmailAndPassword(document.getElementById('email').value.trim(),document.getElementById('password').value);form.classList.add('hidden');verify();}catch(error){setStatus(error.message||'Connexion impossible.','error');}});
auth.onAuthStateChanged(user=>{clearTimeout(timer);form.classList.toggle('hidden',Boolean(user));if(user)verify();else setStatus('Reconnectez-vous à JwetPro pour consulter cette inscription.');});
document.getElementById('share-registration').addEventListener('click',event=>window.JwetproShare?.open({type:'registration',championshipId:event.currentTarget.dataset.championshipId}));
