const playerFirebaseConfig={apiKey:'AIzaSyD_Hbkc00HfJDmtw-2KSR4b9AbsThFt8vg',authDomain:'mopyonlakay.firebaseapp.com',projectId:'mopyonlakay',storageBucket:'mopyonlakay.firebasestorage.app',messagingSenderId:'307157893690',appId:'1:307157893690:web:4e5a033d13d54ce86feb03'};
const playerEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const playerHt=()=>localStorage.getItem('jwetpro-language')==='ht';
const playerText=(fr,ht)=>playerHt()?ht:fr;
const playerState=document.querySelector('[data-player-state]');
const socialId=String(new URLSearchParams(location.search).get('id')||'').trim();
let playerPayload=null;
let playerBusy=false;
const playerInitials=name=>String(name||'JW').split(/\s+/).filter(Boolean).map(part=>part[0]).join('').slice(0,2).toUpperCase();
const playerAvatar=profile=>{const image=/^https:\/\//.test(profile.avatarUrl||'')?profile.avatarUrl:/^[A-Za-z0-9._-]+$/.test(profile.imageName||'')?`./src/profilimage/${encodeURIComponent(profile.imageName)}`:'';return `<span class="player-avatar"${image?` style="background-image:url('${playerEscape(image)}')"`:''}>${image?'':playerEscape(playerInitials(profile.displayName))}</span>`};
const renderPlayer=()=>{
  if(!playerPayload)return;const {profile,viewer}=playerPayload;document.title=`${profile.displayName} — JWETPRO`;
  const simulation=profile.playerType==='simulated';const followLabel=viewer.following?playerText('Abonné','W ap swiv'):viewer.followedBy?playerText('Suivre en retour','Swiv an retou'):playerText('Suivre','Swiv');
  const messageEnabled=viewer.mutual&&!simulation&&!viewer.blocked;
  playerState.innerHTML=`<div class="player-cover"></div><div class="player-content">${playerAvatar(profile)}<div class="player-identity"><div><p class="player-kicker">${simulation?playerText('JOUEUR SIMULÉ','JWÈ SIMILE'):playerText('JOUEUR JWETPRO','JWÈ JWETPRO')}</p><h1>${playerEscape(profile.displayName)}</h1><p>${viewer.mutual?playerText('Vous vous suivez mutuellement','Nou swiv youn lòt'):profile.profilePublic?playerText('Profil public vérifié','Pwofil piblik verifye'):playerText('Profil à visibilité limitée','Pwofil ki limite')}</p></div><div class="player-actions">${viewer.self?'':`<button class="player-action primary" type="button" data-player-follow ${viewer.blocked?'disabled':''}>${followLabel}</button><button class="player-action" type="button" data-player-message ${messageEnabled?'':'disabled'}>${playerText('Écrire','Ekri')}</button><div class="player-menu"><button class="player-action player-more" type="button" data-player-more aria-label="${playerText('Plus d’actions','Plis aksyon')}">•••</button><div class="player-menu-list" data-player-menu hidden><button type="button" data-player-report>${playerText('Signaler','Rapòte')}</button>${simulation?'':`<button class="danger" type="button" data-player-block>${viewer.blockedByViewer?playerText('Débloquer','Debloke'):playerText('Bloquer','Bloke')}</button>`}</div></div>`}</div></div><div class="player-stats"><div class="player-stat"><span>${playerText('Abonnés','Moun k ap swiv')}</span><strong>${Number(profile.followerCount||0).toLocaleString('fr-FR')}</strong></div>${profile.profilePublic||simulation?`<div class="player-stat"><span>${playerText('Niveau','Nivo')}</span><strong>${playerEscape(profile.level||'Débutant')}</strong></div><div class="player-stat"><span>${playerText('Points','Pwen')}</span><strong>${Number(profile.points||0).toLocaleString('fr-FR')}</strong></div><div class="player-stat"><span>${playerText('Matchs','Match')}</span><strong>${Number(profile.matchesPlayed||0).toLocaleString('fr-FR')}</strong></div><div class="player-stat"><span>${playerText('Victoires','Viktwa')}</span><strong>${Number(profile.wins||0).toLocaleString('fr-FR')}</strong></div>`:''}</div>${!profile.profilePublic&&!simulation?`<div class="player-private">${playerText('Ce joueur a limité les informations visibles. Son identité sociale et son nombre d’abonnés restent disponibles.','Jwè sa a limite enfòmasyon ki vizib. Idantite sosyal li ak kantite moun k ap swiv li rete disponib.')}</div>`:''}<p class="player-toast" data-player-feedback aria-live="polite"></p></div>`;
};
const callable=name=>firebase.app().functions('us-central1').httpsCallable(name);
const reloadPlayer=async()=>{try{const result=await callable('getSocialProfile')({socialId});playerPayload=result.data;renderPlayer()}catch(error){playerState.innerHTML=`<div class="player-error"><strong>${playerText('Profil indisponible','Pwofil la pa disponib')}</strong><p>${playerText('Ce profil est introuvable ou désactivé.','Pwofil sa a pa egziste oswa li dezaktive.')}</p></div>`;console.error('Social profile read failed:',error)}};
document.addEventListener('click',async event=>{
  const more=event.target.closest('[data-player-more]');if(more){document.querySelector('[data-player-menu]')?.toggleAttribute('hidden');return}
  if(playerBusy||!playerPayload)return;const feedback=document.querySelector('[data-player-feedback]');
  if(event.target.closest('[data-player-follow]')){playerBusy=true;try{await callable('setFollow')({targetSocialId:socialId,followed:!playerPayload.viewer.following});await reloadPlayer()}catch(error){feedback.textContent=error?.message||playerText('Action impossible.','Aksyon an pa posib.')}finally{playerBusy=false}}
  if(event.target.closest('[data-player-message]')){playerBusy=true;try{const result=await callable('createDirectConversation')({targetSocialId:socialId});location.href=`./community.html?conversation=${encodeURIComponent(result.data.conversationId)}`}catch(error){feedback.textContent=error?.message||playerText('La conversation ne peut pas être ouverte.','Konvèsasyon an pa ka louvri.')}finally{playerBusy=false}}
  if(event.target.closest('[data-player-block]')){playerBusy=true;try{await callable('setSocialBlock')({targetSocialId:socialId,blocked:!playerPayload.viewer.blockedByViewer});await reloadPlayer()}catch(error){feedback.textContent=error?.message||playerText('Action impossible.','Aksyon an pa posib.')}finally{playerBusy=false}}
  if(event.target.closest('[data-player-report]')){const details=prompt(playerText('Décrivez brièvement le problème :','Dekri pwoblèm nan an kout :'));if(details===null)return;playerBusy=true;try{await callable('createSocialReport')({targetSocialId:socialId,reason:'other',details});feedback.textContent=playerText('Signalement transmis à JWETPRO.','Rapò a voye bay JWETPRO.')}catch(error){feedback.textContent=error?.message||playerText('Signalement impossible.','Rapò a pa ka fèt.')}finally{playerBusy=false}}
});
if(!/^[A-Za-z0-9_-]{1,150}$/.test(socialId)){playerState.innerHTML=`<div class="player-error"><strong>${playerText('Profil invalide','Pwofil la pa valab')}</strong></div>`}else{if(!firebase.apps.length)firebase.initializeApp(playerFirebaseConfig);firebase.auth().onAuthStateChanged(()=>reloadPlayer())}
const shell=document.createElement('script');shell.src='./shared-shell.js?v=20260909-social-v3';document.head.append(shell);
